export function getHipsterTitle() {
	const terms = getTerms();
	let title = getRandomTerm(terms);
	let wordCount = 1;
	const titleLength = Math.floor(Math.random() * (4 - 2 + 1)) + 2;

	do {
		title = title + ' ' + getRandomTerm(terms);
		++wordCount
	} while (wordCount < titleLength);
	return title.toUpperCase();
}

function getRandomTerm(terms) {
	return terms[Math.floor(Math.random() * terms.length)];
}

function getTerms() {
	return [
		'+1',
		'8-bit',
		"90's",
		'actually',
		'aesthetic',
		'american apparel',
		'street art',
		'artisan',
		'asymmetrical',
		'authentic',
		'axe',
		'bahn mi',
		'banjo',
		'banksy',
		'beard',
		'before they sold out',
		'bespoke',
		'bicycle',
		'biodiesel',
		'bitters',
		'blog',
		'brunch',
		'butcher',
		'cardigan',
		'carles',
		'chia',
		'chic',
		'chillwave',
		'church-key',
		'cleanse',
		'cold-pressed',
		'craft beer',
		'cray',
		'cred',
		'cronut',
		'deep v',
		'denim',
		'direct trade',
		'disrupt',
		'distillery',
		'DIY',
		'dreamcatcher',
		'Echo Park',
		'ennui',
		'ethical',
		'Etsy',
		'fanny pack',
		'farm-to-table',
		'fashion',
		'fixie',
		'flannel',
		'flexitarian',
		'FOMO',
		'food truck',
		'foodie',
		'forage',
		'freegan',
		'fuck boy',
		'gastropub',
		'gentrify',
		'gluten-free',
		'hashtag',
		'heirloom',
		'Helvetica',
		'hoodie',
		'indie',
		'iphone',
		'irony',
		'kale chips',
		'keffiyeh',
		'keytar',
		'kickstarter',
		'kitsch',
		'kogi',
		'laserdisc',
		'leggings',
		'letterpress',
		'life',
		'literally',
		'lo-fi',
		'locavore',
		'lol',
		'malort',
		'marfa',
		'master',
		'meditation',
		'meggings',
		'meh',
		'migas',
		'mixtape',
		'mlkshk',
		'moon',
		'mumblecore',
		'mustache',
		'narwhal',
		'neutra',
		'next level',
		'noise-rock',
		'normcore',
		'occupy',
		'Odd Future',
		'organic',
		'PBR',
		'photo booth',
		'pickled',
		'Pinterest',
		'Pitchfork',
		'plaid',
		'polaroid',
		'pop-up',
		'pork belly',
		'Portland',
		'post-ironic',
		'pour-over',
		'pug',
		'put a bird on it',
		'quinoa',
		'raw denim',
		'retro',
		'roof party',
		'salvia',
		'scenester',
		'schlitz',
		'seitan',
		'selfies',
		'selvage',
		'semiotics',
		'shabby',
		'shoreditch',
		'shorts',
		'skateboard',
		'slow-carb',
		'specs',
		'stumptown',
		'sustainable',
		'swag',
		'tattoo',
		'tattooed',
		'taxidermy',
		'tilde',
		'tofu',
		'Toms',
		'tote bag',
		'tousled',
		'trust fund',
		'truffaut',
		'try-hard',
		'tumblr',
		'twee',
		'typewriter',
		'umami',
		'vegan',
		'VHS',
		'Vice',
		'vinegar',
		'vinyl',
		'viral',
		'wayfarers',
		'wire-rimmed glasses',
		'wolf',
		'xoxo',
		'yolo',
		"you probably haven't heard of them"
	];
}